import { motion } from 'framer-motion'
import useStore from '../../store/useStore'

export default function ShareableProfileCard({ profile, onClose }) {
  const showToast = useStore((s) => s.showToast)

  const handleCopy = () => {
    const lines = [
      `LOCUS Resident Profile`,
      `━━━━━━━━━━━━━━━━━━━━━━`,
      ``,
      `Lifestyle: ${profile.lifestyleType}`,
    ]

    if (profile.budgetTier) {
      lines.push(`Budget: ${profile.budgetTier}`)
    }

    lines.push(`Search Intent: ${profile.searchIntent}`)

    if (profile.prioritySummary.length > 0) {
      lines.push(``, `Priorities: ${profile.prioritySummary.join(', ')}`)
    }

    if (profile.topInterests.length > 0) {
      lines.push(`Interests: ${profile.topInterests.join(', ')}`)
    }

    if (profile.topNeighborhoods.length > 0) {
      lines.push(``, `Explored Neighborhoods:`)
      profile.topNeighborhoods.forEach(n => {
        lines.push(`  - ${n.name} (${n.count} views)`)
      })
    }

    if (profile.traits.length > 0) {
      lines.push(``, `Traits: ${profile.traits.map(t => t.label).join(', ')}`)
    }

    lines.push(``, `Profile Strength: ${profile.profileStrength}%`)
    lines.push(``, `Generated by LOCUS — Neighborhood Intelligence, Debiased`)

    navigator.clipboard.writeText(lines.join('\n')).then(() => {
      showToast('Profile copied to clipboard')
    }).catch(() => {
      showToast('Could not copy to clipboard')
    })
  }

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.95 }}
      transition={{ duration: 0.2 }}
      className="fixed inset-0 z-[60] flex items-center justify-center p-4"
      onClick={onClose}
    >
      <div className="absolute inset-0 bg-black/50" />

      <motion.div
        initial={{ y: 20 }}
        animate={{ y: 0 }}
        className="relative w-full max-w-sm rounded-[16px] overflow-hidden shadow-2xl"
        onClick={(e) => e.stopPropagation()}
        style={{ background: 'var(--bg-surface)' }}
      >
        {/* Card Header */}
        <div className="px-6 pt-6 pb-4 text-center border-b border-[var(--border)]">
          <div className="inline-flex items-center gap-1.5 text-[var(--accent)] text-[13px] font-semibold tracking-[0.04em] uppercase mb-1">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M12 2L2 7l10 5 10-5-10-5z" />
              <path d="M2 17l10 5 10-5" />
              <path d="M2 12l10 5 10-5" />
            </svg>
            LOCUS
          </div>
          <h3 className="text-[18px] font-bold text-[var(--text-primary)]">Locus Resident</h3>
          <p className="text-[12px] text-[var(--text-muted)] mt-0.5">Neighborhood Profile</p>
        </div>

        {/* Card Body */}
        <div className="px-6 py-5 space-y-4">
          {/* Lifestyle Badge */}
          <div className="flex justify-center">
            <span
              className="px-4 py-2 rounded-full text-[13px] font-semibold border"
              style={{
                color: 'var(--accent)',
                borderColor: 'var(--accent)',
                background: 'color-mix(in srgb, var(--accent) 10%, transparent)',
              }}
            >
              {profile.lifestyleType}
            </span>
          </div>

          {/* Budget */}
          {profile.budgetTier && (
            <div className="text-center">
              <span className="text-[12px] text-[var(--text-muted)]">Budget Tier: </span>
              <span className="text-[12px] font-medium text-[var(--text-secondary)]">{profile.budgetTier}</span>
            </div>
          )}

          {/* Priorities */}
          {profile.prioritySummary.length > 0 && (
            <div>
              <span className="text-[11px] font-medium uppercase tracking-[0.04em] text-[var(--text-muted)] block mb-1.5">Priorities</span>
              <div className="flex flex-wrap gap-1.5">
                {profile.prioritySummary.map((label) => (
                  <span key={label} className="px-2.5 py-1 text-[11px] rounded-[5px] border border-[var(--border)] bg-[var(--bg-elevated)] text-[var(--text-secondary)]">
                    {label}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Interests */}
          {profile.topInterests.length > 0 && (
            <div>
              <span className="text-[11px] font-medium uppercase tracking-[0.04em] text-[var(--text-muted)] block mb-1.5">Interests</span>
              <div className="flex flex-wrap gap-1.5">
                {profile.topInterests.map((interest) => (
                  <span key={interest} className="px-2.5 py-1 text-[11px] rounded-[5px] border border-[var(--border)] bg-[var(--bg-elevated)] text-[var(--text-secondary)]">
                    {interest}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Top Neighborhoods */}
          {profile.topNeighborhoods.length > 0 && (
            <div>
              <span className="text-[11px] font-medium uppercase tracking-[0.04em] text-[var(--text-muted)] block mb-1.5">Explored</span>
              <div className="space-y-1">
                {profile.topNeighborhoods.slice(0, 3).map((n) => (
                  <div key={n.id} className="flex items-center justify-between text-[12px]">
                    <span className="text-[var(--text-primary)]">{n.name}</span>
                    <span className="text-[var(--text-muted)]">{n.count}x</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Traits */}
          {profile.traits.length > 0 && (
            <div className="flex flex-wrap gap-1.5 justify-center pt-1">
              {profile.traits.map((trait) => (
                <span key={trait.label} className="inline-flex items-center gap-1 px-2.5 py-1 text-[11px] rounded-full bg-[var(--bg-elevated)] text-[var(--text-secondary)]">
                  <span aria-hidden="true">{trait.icon}</span>
                  {trait.label}
                </span>
              ))}
            </div>
          )}
        </div>

        {/* Card Footer */}
        <div className="px-6 pb-5 flex gap-2">
          <button
            onClick={handleCopy}
            className="flex-1 py-2.5 rounded-[8px] text-[13px] font-medium bg-[var(--accent)] text-white hover:bg-[var(--accent-hover)] transition-colors"
          >
            Copy to Clipboard
          </button>
          <button
            onClick={onClose}
            className="px-4 py-2.5 rounded-[8px] text-[13px] font-medium border border-[var(--border)] text-[var(--text-secondary)] hover:border-[var(--border-active)] transition-colors"
          >
            Close
          </button>
        </div>
      </motion.div>
    </motion.div>
  )
}
